accounts/urls.py
"""accounts URL configuration
accounts отвечает за управление пользователями и состоит целиком из модели

"""
from django.conf.urls import url, include
from .forms import MyAuthForm
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    url(r'^logout/', LogoutView.as_view(next_page = '/')),
    url(r'^$', LoginView.as_view(redirect_authenticated_user = True,
        template_name='accounts/login.html',
        authentication_form=MyAuthForm),
    name="auth"),
    ]

dataviewer/urls.py
'''dataviewer URL Configuration

dataviewer отвечает за предоставление пользователю доступных ему документов
'''

from django.conf.urls import url, include
from . import views as PostViews
from django.views.generic import ListView
from .models import Post
from .forms import UploadForm


urlpatterns = [
    url(r'^files/$', PostViews.Files.as_view(template_name="dataviewer/files.html"), name='files'),   
    url(r'^upload/', PostViews.Upload.as_view(template_name="dataviewer/upload.html"), name='upload'),
    url(r'^update/(?P<pk>\d+)/$', PostViews.Update.as_view(template_name="dataviewer/update.html"), name='update'),
    ]

praktika/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

def generic_redirect(request):
    return redirect('/auth/')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('accounts.urls')),
    url(r'^data/', include('dataviewer.urls', namespace="dataviewer")),
    url(r'^$', generic_redirect, name="generic_redirect"),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dataviewer/models.py
import os
from django.db import models
from django.contrib.auth.models import Group
from django.template.defaultfilters import slugify
from django.conf import settings
from django.utils.crypto import get_random_string

""" 
Класс Post -- это модель для представления загруженных в систему файлов.
Поля модели:
    title - название загруженного файла
    upload_date - дата загрузки
    uploaded_by - пользователь, загрузивший файл
    file_body - сам файл
    belongs_to - группа(отдел), которой принадлежит файл
    tags - теги, по которым проще найти файл
"""
class Post(models.Model):
    def upload_path(instance, filename):
        file_as_list = filename.split('.')
        file_as_list[0] += ('_' + get_random_string(8))
        filename = '.'.join(file_as_list)
        return 'departments/{0}/{1}'.format(instance.belongs_to, filename)

    def filename(self):
        return os.path.basename(self.file_body.name)
    title       = models.CharField(max_length = 256)
    upload_date = models.DateTimeField(auto_now = False, auto_now_add = True)
    uploaded_by = models.ForeignKey(settings.AUTH_USER_MODEL, default = 1)
    file_body   = models.FileField(upload_to = upload_path)
    belongs_to  = models.CharField(max_length = 256)

    tags = models.CharField(max_length = 256, blank = True)
    # представляет теги в виде списка
    def get_tag_list(self):
        if self.tags != '':
            return self.tags.split(',')
        else:
            return ''

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return "/data/files/"

dataviewer/forms.py
from django.forms import ModelForm
from .models import Post

# Форма на основе модели Post

class UploadForm(ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'file_body', 'tags', )
        labels = {
                'title': 'Название',
                'file_body': '',
                'tags': 'Добавить теги',
                }
    def __init__(self, *args, **kwargs):
        super(UploadForm, self).__init__(*args, **kwargs)
        self.fields['title'].required = False

class UpdateForm(ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'tags', )
        labels = {
                'title': 'Изменить название',
                'tags': 'Изменить теги',
                }
    def __init__(self, *args, **kwargs):
        super(UpdateForm, self).__init__(*args, **kwargs)
        self.fields['title'].required = False

dataviewer/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic.edit import UpdateView
from .forms import UploadForm, UpdateForm
from django.http import HttpResponseRedirect
from django.db.models import Q
from .models import Post
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator

# Декораторы login_required работают для всего приложения dataviewer, поэтому при объявлении классов не требуются.

""" 
Класс Files  -- это вид, отображаемый при просмотре пользователем доступных ему файлов и поиске через строку поиска или теги.
"""
class Files(View):
    template_name = 'dataviewer/files.html'
    def get(self, request):
        # Отображение только доступных пользователю файлов
        if request.user.is_staff or request.user.is_superuser:
            posts_to_display = Post.objects.all()
        else:
            all_user_groups = request.user.groups.all()
            q_objects = Q()
            for group in all_user_groups:
                q_objects |= Q(belongs_to__contains=group)
            posts_to_display = Post.objects.filter(q_objects)
        # Поиск
        query = request.GET.get('q')
        if query:
            posts_to_display = posts_to_display.filter(
                    Q(title__icontains=query) |
                    Q(tags__icontains=query) 
                    )
        tags = request.GET.get('t')
        if tags:
            posts_to_display = posts_to_display.filter(tags__icontains=tags)
        context = {
                'posts_to_display': posts_to_display,
                }
        return render(request, self.template_name, context)


""" 
Класс Upload -- это вид, отображаемый при загрузке файла в систему. Загруженный файл автоматически присваивается той группе, в которой находится пользователь, загрузивший его.
"""
@method_decorator(permission_required("dataviewer.add_post", raise_exception=True), name="dispatch")
class Upload(View):
    form_class = UploadForm
    template_name = 'dataviewer/upload.html'
    def post(self, request):
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit = False)
            instance.uploaded_by = request.user
            # Если в будущем будет несколько групп, не являющихся отделами, всю эту систему нужно будет переделать
            instance.belongs_to = request.user.groups.all().exclude(name="Uploaders")[0].name
            if instance.title == '':
                instance.title = instance.filename()
            instance.save()
            return HttpResponseRedirect('/data/files')
        return render(request, self.template_name, {'form': form})
    def get(self, request):
        # Убрать предупреждения при первой загрузке с помощью or None
        form = UploadForm(request.POST or None, request.FILES or None)
        return render(request, self.template_name, {'form': form})

# @method_decorator(permission_required("dataviewer.change_post", raise_exception=True), name="dispatch")
# class Update(View):
    # form_class = UpdateForm
    # template_name = 'dataviewer/update.html'
    # def post(self, request, id=None):
        # instance = get_object_or_404(Post, id=id)
        # form = UpdateForm(request.POST or None)
        # if form.is_valid():
            # if instance.title == '':
                # instance.title = instance.filename()
            # instance.save()
            # return HttpResponseRedirect('/data/files')
        # return render(request, self.template_name, {'form': form, 'instance': instance})
    # def get(self, request, id):
        # form = UploadForm(request.POST or None)
        # return render(request, self.template_name, {'form': form})

@method_decorator(permission_required("dataviewer.change_post", raise_exception=True), name="dispatch")
class Update(UpdateView):
    model = Post
    form_class = UpdateForm
    def form_valid(self, form):
            form.instance.uploaded_by = self.request.user
            return super(UpdateView, self).form_valid(form)

dataviewer/templates/dataviewer/create.html
{% extends header.html %}
{% block body %}
<h2>Create:</h2>
{% endblock %}

dataviewer/templates/dataviewer/files.html
{% extends "header.html" %}

{% block content %}
<div class="files-list panel panel-primary">
    <div class="panel-heading">
        <h3>Список доступных файлов</h3>
    </div>
    <div class="panel-body ">
        <table id="files-table" class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th class="file-upload-date">Дата</th>
                    <th>Название файла</th>
                    <th class="file-tags">Теги</th>
                </tr>
            </thead>
            <tbody>
                <!-- чтобы не проверять по сто раз -->
                {% with perms.dataviewer.change_post as can_change_post %}
                    {% for post in posts_to_display %}
                    <tr>
                        <td class="file-upload-date">{{ post.upload_date|date:"d.m.Y" }}</td>
                        <td><a href="{{ post.file_body.url }}" download>{{ post.title }}</a>
                            {% if can_change_post %}
                                <a href="{% url 'dataviewer:update' pk=post.id %}"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></a>
                            {% endif %}</td>
                        <td class="file-tags">
                            {% if post.get_tag_list == "" %}
                            <p class="notag">Теги отсутствуют</p>
                            {% else %}
                                <p>
                                    {% for tag in post.get_tag_list %}
                                    <a class="tag-link" href="{{ post.get_absolute_url }}?t={{ tag }}">{{ tag }}</a>,&#160;
                                    {% endfor %}
                                </p>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                {% endwith %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

dataviewer/templates/dataviewer/update.html
{% extends "header.html" %}

{% block content %}
<div id="file-upload-form" class="form-wrapper">
    <form method="post" class="upload-form">
    {% csrf_token %}
    {{ form.as_p }}
    <p class="text-helper">Теги вводятся через запятую без пробелов.</p>
    <div class="btn-group">
        <button type="submit" class="btn btn-primary">Подтвердить</button>
        <a href="{% url 'dataviewer:files' %}" class="btn btn-default">Назад</a>
    </div>
    </form>
</div>
{% endblock %}

dataviewer/templates/dataviewer/upload.html
{% extends "header.html" %}

{% block content %}
<div id="file-upload-form" class="form-wrapper">
    <h3>Выберите файл:</h3>
    <form method="post" enctype="multipart/form-data" class="upload-form">
    {% csrf_token %}
    {{ form.as_p }}
    <p class="text-helper">Теги вводятся через запятую без пробелов.</p>
    <div class="btn-group">
        <button type="submit" class="btn btn-primary">Подтвердить</button>
        <a href="{% url 'dataviewer:files' %}" class="btn btn-default">Назад</a>
    </div>
    </form>
</div>
{% endblock %}